// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Use environment variables for security in production
// In development, you might hardcode for simplicity, but variables are recommended
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://izzkpekaddorvymiubju.supabase.co"; // Your provided URL
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6emtwZWthZGRvcnZ5bWl1Ymp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MDkzOTksImV4cCI6MjA2Mzk4NTM5OX0._PGo9tOGTDYJImPnwW3H9XL2OgmDOZi2xQWg0ad7F5I"; // Your provided key

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);